project 'OpenDrone.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'OpenDrone' do
  pod 'AppCenter/Crashes', '~> 2.4.0'
  pod 'AppCenter/Analytics', '~> 2.4.0'
  pod 'AppCenterReactNativeShared', '~> 2.4.0'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for OpenDrone
  pod 'TcpSockets', :path => '../node_modules/react-native-tcp'

  platform :ios, '9.0'
  pod 'react-native-udp', :path => '../node_modules/react-native-udp'

  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

end
